name = "openai-proxy"
main = "index.js"
compatibility_date = "2023-10-30"

[vars]
# This is where you'd define non-secret environment variables

# For your secret API key, use the secret command shown below instead of putting it here